import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./BootstrapClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthContextProvider } from "@/contexts/AuthContext";
import { ThemeContextProvider } from "@/contexts/ThemeContext";
import { NotificationContextProvider } from "@/contexts/NotificationContext";
import AppLayoutWrapper from "@/components/app-layout-wrapper/AppLayoutWrapper";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
      <body>
        <BootstrapClient />
        <ThemeContextProvider>
          <AuthContextProvider>
            <NotificationContextProvider>
              <AppLayoutWrapper>
                {children}
              </AppLayoutWrapper>
            </NotificationContextProvider>
          </AuthContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
